name: Integration

on:  # yamllint disable-line rule:truthy
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  merge_group:
    types: ["checks_requested"]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running'
        required: false
        default: 'No reason provided'

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: Update apt repositories
        run: sudo apt update
      - name: Install lint dependencies
        run: sudo apt install -y yamllint aspell pre-commit
      - name: Install project dependencies
        run: sudo apt install -y libgpgme-dev libbtrfs-dev libvirt-dev
      - name: "Clone Repository"
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
      - name: Run linters
        run: make lint

  manifest:
    name: "Manifest"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/testdeps
      - name: Install integration test env
        run: |
          sudo apt update
          sudo apt install -y python3-pytest golang
      - name: Run integration tests via pytest
        run: |
          # use "-s" for now for easier debugging
          sudo pytest -s -v test/test_manifest.py

  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/testdeps
      - name: Install integration test env
        run: |
          sudo apt update
          sudo apt install -y python3-pytest golang
      - name: Run integration tests via pytest
        run: |
          # use "-s" for now for easier debugging
          sudo pytest -s -v test/test_build.py

  build-cross:
    name: "Build (Cross-Architecture)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/testdeps
      - name: Install integration test env
        run: |
          sudo apt update
          sudo apt install -y python3-pytest golang libvirt-dev
      - name: Install cross build dependencies
        run: sudo apt install -y qemu-user-static

      - name: Run integration tests via pytest
        run: |
          # use "-s" for now for easier debugging
          sudo pytest -s -v test/test_build_cross.py

  smoke:
    name: "Smoke"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/testdeps
      - name: Install integration test env
        run: |
          sudo apt update
          sudo apt install -y python3-pytest golang asciinema
      - name: Run integration tests via pytest
        run: |
          # use "-s" for now for easier debugging
          sudo pytest -s -v test/test_smoke.py
